language: node_js
node_js:
 - "node"
services:
 - postgresql
addons:
  postgresql: "9.4"
before_script:
 - psql -c 'drop database if exists mydiary_test;' -U postgres
 - psql -c 'create database mydiary_test;' -U postgres
after_success: npm run coverage